version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:12.6
  docker-publisher:
    environment:
      IMAGE_NAME: mee6aas/runtime-nodejs:latest
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  test:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - persist_to_workspace:
          root: .
          paths: .

  build-app:
    executor: nodejs
    steps:
      - attach_workspace:
          at: .
      - run:  npm run build
      - persist_to_workspace:
          root: .
          paths: .


  build-image:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths: ./image.tar

  publish:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Load archived Docker image
          command: docker load -i ./image.tar
      - run:
          name: Publish Docker image
          command: |
            echo "$REPO_PASSWORD" | docker login -u "$REPO_USERNAME" --password-stdin
            docker push $IMAGE_NAME

workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build-app:
          requires:
            - test
          filters:
            branches:
              only: master
      - build-image:
          requires:
            - build-app
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build-image
          filters:
            branches:
              only: master